### ISSUE TITLE
how to load from gogocdn

### ISSUE THREAD

**Issue by icewyvrn** [astrolabio1417/animeyubi-streamani#1]
how does this work? https://animeyubiv7.herokuapp.com/api/v2/video?url=

i want to load videos from gogocdn too hehe

**Comment by astrolabio1417** [comment]
Download the file from server and serve it as stream file.

**To avoid forbidden request.**
try to download the file and check/copy the headers of the request. you can use the headers to download the file or forbidden if you didn't include the correct headers. [referer, Range, user-agent?, Accept-Ranges]

And this one.
https://stackoverflow.com/questions/22894211/how-to-resume-file-download-in-python

sample server using flask. I'm newbie on this type of thing ✌️ . For html video only.   
localhost:5000/v?q=VIDEO_URL

            from flask import Flask
            from flask import Response, request
            import requests

            application = Flask(__name__)

            @application.route("/")
            def index():
                return Response("HELLO")

            @application.route("/v")
            def v():
                url =  request.args.get('q', False)

                headers = {
                    'referer': str(url.split(".com")[0]) + ".com",
                    'user-agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
                    'Range': request.headers.get('Range', 'bytes=0-'),
                    'Accept_Ranges': 'bytes'
                }

                response = requests.get(url=url, headers=headers, stream=True)

                return Response(
                    response.raw,
                    content_type=response.headers.get('content-type'),
                    headers = {
                        'Content-Disposition': 'attachment; filename=',
                        'Content-Range': str(response.headers.get('Content-Range')),
                        'Content-Length': str(response.headers.get('Content-Length'))
                    },
                    status=response.status_code,
                )
`

**Comment by icewyvrn** [comment]
thank you! works perfectly
